name: Build .NET Framework Chatbot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: CypherChatbot.sln  # Make sure this matches your solution file name

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build with MSBuild
      run: msbuild $env:Solution_Name /p:Configuration=Debug /t:Rebuild
